### ISSUE TITLE
Create Config System

### ISSUE THREAD

**Issue by Ximidar** [Ximidar/NodeLauncher#3]
# Config System

## Overview
Flotilla needs a way to update all nodes with a config change. Currently there are only hard coded values in each node. I would like a way for the Node Launcher to read the config, then share the different Config Options over the Nats Interface. 

## Tasks
- [ ] Use Viper to load config file
- [ ] Create a DataStructure package to query NATS for a config
- [ ] Create a NATS package for sharing the config over NATS
- [ ] Figure out a way to share the NATS Port to each node (CL Arguments?)
